FROM node:20-alpine

WORKDIR /app

# копируем только package.json
COPY frontend/package*.json ./

# ❗ Добавляем очистку перед установкой
RUN rm -rf node_modules package-lock.json && npm install --legacy-peer-deps

# копируем код
COPY frontend/ .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
